# Generated by Django 4.1.1 on 2022-10-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images_uploader',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='images_uploader',
            name='family_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='images_uploader',
            name='unique_token',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
