# Generated by Django 4.1.1 on 2022-10-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_images_uploader_category_images_uploader_family_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliced_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_Token', models.CharField(blank=True, max_length=80)),
                ('Family_name', models.CharField(blank=True, max_length=80)),
                ('Images', models.ImageField(upload_to='static/Sliced')),
            ],
        ),
    ]
