# Generated by Django 4.1.1 on 2022-10-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_sliced_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Ceren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=80)),
                ('Email', models.EmailField(blank=True, max_length=80)),
                ('Password', models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
