# Generated by Django 4.1.1 on 2022-10-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_user_ceren'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ceren',
            name='Encrypted_image',
            field=models.CharField(blank=True, max_length=450),
        ),
    ]
