# Generated by Django 4.1.1 on 2022-10-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_remove_user_ceren_encrypted_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ceren',
            name='Password',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
